### ISSUE TITLE
Support Multi-root Workspaces

### ISSUE THREAD

**Issue by talbenmoshe** [jakob101/RelativePath#21]
This extension is awesome! But i'm unable to use it since I switched to the new multi-root feature in vscode.

When I'm in a certain project, I get file suggestions only from a different project in the workspace.

**Comment by jakob101** [comment]
Oh! I will take a look. Thanks!

________________________________

**Comment by rrag** [comment]
I have used this extension and love it. the solution is described [here](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath)

Looks like instead of setting `this._workspacePath` to `rootPath` in [ctor](https://github.com/jakob101/RelativePath/blob/master/src/extension.ts#L41) 

```
workspace.getWorkspaceFolder(window.activeTextEditor.document.uri)
```

should be used as the `_workspacePath`
at https://github.com/jakob101/RelativePath/blob/master/src/extension.ts#L180

Am I in the right track? I have never worked on a vscode extension, and will be happy to PR if you can direct me to the right path

**Comment by jakob101** [comment]
That’s correct!
You’d make me very happy if you could propose a pr :)

Creating an extension is pretty easy - open vscode with the cloned repo and press F5. It will open a new VSCode window where you run the extension. The old one has the debugger.

Let me know if you need more pointers :)

And thanks !!! 👋🙏

________________________________

**Comment by rrag** [comment]
There is caching of all the files in the worspace. Since this cache is done on initialization in the constructor of the extension there are a few problems

1. the same list of files are displayed everytime, the list depends on the project the command `extension.relativePath` is executed the first time
2. if I open the command `extension.relativePath` the first time from the `welcome` tab and not a real file in a workspace, I would get an error 

![deepinscreenshot_select-area_20171217094851](https://user-images.githubusercontent.com/10691183/34081227-8ec8fc7a-e30f-11e7-958f-b045aa3114bd.png)

```
        const editor = window.activeTextEditor;
        const resource = editor.document.uri;
        const folder = workspace.getWorkspaceFolder(resource)
```

since `window.activeTextEditor` will be undefined in the `welcome` page

I think I can solve the first problem by adding a `this._watcher.onDidChange((e: Uri) => `

and comparing the prior workspace folder and the current workspace folder from `e`

if they are different do a `this.updateFiles(false)` else do nothing.

But for the second problem I am not sure what I can do. may be a helpful message to say that `window.activeTextEditor` is not there so execute the same command from a valid file,

If we go with the above info message display approach, then we can also use the same when you open up the command from a folder which is *not* a workspace folder also

I would like to hear your thoughts on this.

Also unrelated, I had to upgrade to latest dependencies and typescript config like

https://github.com/Microsoft/vscode-extension-samples/blob/master/basic-multi-root-sample/package.json
https://github.com/Microsoft/vscode-extension-samples/blob/master/basic-multi-root-sample/tsconfig.json

as described in https://code.visualstudio.com/updates/v1_6#_extension-authoring

**Comment by rrag** [comment]
https://github.com/jakob101/RelativePath/pull/22

**Comment by jakob101** [comment]
Sorry man, had some hectic days. Thanks for the PR, it looks good to me! You found great solutions to some issues.

**Comment by rrag** [comment]
Sorry for the delay, been busy with vacation time :) I will get to this this week
